defaults:
  - base
  - _self_

task_conf:
  - name: "craft"
    text: "craft item crafting_table" 

reward_conf:
  - event: "craft_item"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "crafting_table"
    identity: "craft crafting_table"
  
init_inventory: 
  - slot: 14
    type: oak_planks
    quantity: ">3"

need_crafting_table: False
need_gui: True