defaults:
  - base
  - _self_

# Optional: choose biomes with trees
candidate_preferred_spawn_biome: 
  - forest
  - plains

# Optional commands (tool or spawning logs). Remove if not needed.
command:
  - "/give @s minecraft:wooden_axe"
  # - "/execute as @p at @s run fill ~1 ~ ~1 ~5 ~10 ~5 minecraft:oak_log"

task_conf:
  - name: "collect"
    text: "pickup:oak_log"

reward_conf:
  - event: "pickup"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "oak_log"
    identity: "collect oak_log"

init_inventory:
  - slot: 0
    type: "wooden_axe"
    quantity: 1

mobs: []